---
title: "WritingExercise02"
---

# Instructions

Each of the writing samples below violates at least one of Strunk and White’s Principles of Composition. Read the samples critically, and edit to improve them. Remember to make a commit to save your changes when you are done. 

# Writing Samples

## Principle: use the active voice

An analysis was performed by scientists to understand the metabolic pathways in bacteria.
Scientists performed analysis to understand the metabolic pathway in bacteria.

## Put statements in positive form.

Bacteria that metabolize glucose are important for fermentation.

## Use definite, specific, concrete language.

Zhang et al (2016) indicate that algae can be useful in biofuel production.

## Omit needless words.

Investigations into the metabolic pathways of *Aspergillus niger* can be engineered to enhance the production of citric acid, a key ingredient in industrial applications.
Investigations into the metabolic pathways of *Aspergillus niger* demonstrate it can be engineered to enhance the production of citric acid. 

## Express coordinate ideas in similar form.

Microbes are used to produce a range of fermented foods: yeast to produce bread and alcoholic products including beer, wine, and sake; bacillus and natto; cheese, fermented vegetables, and pickles made by lactic acid bacteria; fermentation is even important for production of coffee and chocolate. 

## Keep related words together.

Microbes that are able, under certain specific environmental conditions and following appropriate pre-treatment of the substrate, to degrade plastics such as polyethylene (PET) using specific enzymes (e.g., PETase) include bacteria such as *Ideonella sakaiensis*. 

*Ideonella Sakaiensis* is able to degrade plastics such as PET using specific enzymes (e.g. PETase), under certain environmental conditions and following appropriate pre-treatment of the substrate.

## In summaries, keep to one tense.

The engineered *E. coli* strain was grown in a 5 L bioreactor for 24 hours. 
The glucose concentration decreased steadily, while the optical density increased to 8.4. The culture is harvested at the end of fermentation by centrifugation and the recombinant enzyme purified using affinity chromatography. 
The purified enzyme showed a specific activity of 42 U/mg and is suitable for use in the subsequent biocatalytic process.

## Place the emphatic words of a sentence at the end.

Genomic Data suggests that any given species of Streptomyces can produce a variety of antibiotics. 

