---
title: "WritingExercise05"
---

# Reflect on your own skills and development as a writer

- What are the areas you think you are good at? Where can you improve?
#I can improve my grammar and abilty to proofread as there are often common mistakes in my work. I feel like i have a good use of active tone however i could improve mu use of speicific concrete language.

- How will you further develop your skills over the coming year? Can you make a specific, detailed plan?
#To improve practice is key. Going over my past writing samples and trying to note areas of improvement will help to idenitfy more areas where i can improve. Another plan will be to read or write one piece of scientific writing a week, in order to improve my objective tone.

# Reflect on writing more generally
It is a struggle to write words from thought, and transfer my thoughts into text that has a concise flow and structure.

- What principles of composition discussed today did you find most useful?
- Despite the obvious sexism. Thunks and White rules helped me the most in understanding how to write a concise and structured paragraph.

- If you were going to formulate your own writing rules, what would they be?
Check Grammar.

# Commit your reflections to writing

Compose a paragraph summarizing your reflections. Remember to use the "commit" process to save your changes when you are finished.
While it has been previous noted that improvement to grammar and punctuation is the easiest way to improve my writing, today has highlighted how crucial it truly is to convey exact meaning with every sentence. I have come to understand that there are many facets of wriitng i can strengthen my writing, however there is equally as many reasources available to me.
